---
title: "Cuzzi's PhD Thesis Plots"
output: html_notebook
---

```{r}
rm(list=ls())
library('dplyr')
library('ggplot2')
library("readxl")
library("lubridate")
library('padr')
library('here')
library("PerformanceAnalytics")

source(file.path(getwd(), 'plots', 'plot_funcs.R'))
source(file.path(getwd(), 'models', 'utils.R'))
source(file.path(getwd(), 'plots', 'plot_funcs.R'))

MODEL <- "rolling-ols"
STRATEGY_TYPE <- "scale"
OUTPUT_PATH <- file.path(here(), 'src', 'data', 'outputs', MODEL)
TARGET <- "SGD"
SCALE_TYPE <- "rolling_scale"
FREQ = "weekly"
WINDOW_SIZE <- 52 * 2
INTERCEPT <- FALSE
THRESHOLD <- 1

if (FREQ == "monthly"){
  FREQ_INT <- 12
}else if (FREQ == "weekly"){
  FREQ_INT <- 52
}

if (INTERCEPT == T){
  intercept_tag <- "intercept"
}else{
  intercept_tag <- "nointercept"
}

```

```{r}
strategy_output_path <- file.path(OUTPUT_PATH,
                                  SCALE_TYPE,
                                  paste0("backtest_results_freq=", FREQ,
                                           "_window-size=", WINDOW_SIZE,
                                           "_strategy-type=", STRATEGY_TYPE,
                                           "_", intercept_tag,
                                           "_threshold=", THRESHOLD, ".rds"))
# read outputs
output <- readRDS(strategy_output_path)

# prepare outputs to read
pnl_df <- output$pnl
cum_pnl_df <- output$cum_pnl
returns_df <- output$returns
cum_returns_df <- output$cum_returns
positions_df <- output$positions
vol_adj_returns <- output$vol_adj_returns
cum_vol_adj_returns <- output$cum_vol_adj_returns
cointegration_error <- output$cointegration_error
```

```{r}
# write.csv(cointegration_error, "cointegration_error.csv")
# write.csv(vol_adj_returns, "vol_adj_returns.csv")
# write.csv(cum_vol_adj_returns, "cum_vol_adj_returns.csv")
```

```{r}
# ggplot(data = cum_pnl_df %>% mutate(portfolio=1+portfolio), mapping = aes(x = date, y = portfolio)) +
#   geom_line() +
#   scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
#   theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#   ggtitle("Cummulative returns of $1 invested in the portfolio")
```

```{r}
# mean <- mean(returns_df$portfolio[returns_df$portfolio!=0])
# vol <- sd(returns_df$portfolio[returns_df$portfolio!=0])
# sharpe <- mean / vol * sqrt(52)
# 
# sharpe
```

```{r}
# ggplot(data = cum_pnl_df %>% select(-portfolio) %>% melt(., "date"),
#        mapping = aes(x = date, y = value, colour = variable, group = variable)) +
#   geom_line() +
#   scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
#   theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#   ggtitle("Cummulative returns of $1 invested in each asset")
```

```{r}
# sharpes <- list()
# i <- 1
# for (col in colnames(pnl_df %>% select(-date))){
#   mean <- mean(pnl_df[[col]][pnl_df[[col]]!=0])
#   vol <- sd(pnl_df[[col]][pnl_df[[col]]!=0])
#   sharpe <- mean / vol * sqrt(52)
#   
#   sharpes[[i]] <- data.table(currency=col, sharpe=sharpe)
#   i <- i + 1
# }
# sharpes <- do.call(rbind, sharpes) %>% as.data.table()
# 
# sharpes
```


```{r}
ggplot(data = cum_vol_adj_returns %>% mutate(portfolio=1+portfolio),
       mapping = aes(x = date, y = portfolio)) +
  geom_line() +
  scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Cummulative returns in % terms (15% vol target)")
```

```{r}
p1 <- ggplot(data = cum_vol_adj_returns %>% mutate(portfolio=1+portfolio),
       mapping = aes(x = date, y = portfolio)) +
  geom_line() +
  scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Cummulative returns in % terms (15% vol target)")
p2 <- ggplot(data = cointegration_error, aes(x = date)) +
  geom_line(aes(y = residual, color = "Residual"), size = 1) +
  geom_line(aes(y = ub, color = "Bounds"), linetype = "dashed", linewidth = 0.8) +
  geom_line(aes(y = lb, color = "Bounds"), linetype = "dashed", linewidth = 0.8) +
  # Add labels and title
  labs(
    title = "Contegration Error (Stratey Signals)",
    y = "Values",
    x = "date",
    color = "Legend"
  ) +
  # Customize colors
  scale_color_manual(values = c("Residual" = "black", "Bounds" = "red")) +
  scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
  # Rotate the x-axis labels for readability
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme(legend.position = "none")
grid.arrange(p1, p2, ncol = 1)
```

```{r}
mean <- mean(vol_adj_returns$portfolio[vol_adj_returns$portfolio!=0])
vol <- sd(vol_adj_returns$portfolio[vol_adj_returns$portfolio!=0])
sharpe <- mean / vol * sqrt(52)

sharpe
```

```{r}
mean <- mean(vol_adj_returns$portfolio)
vol <- sd(vol_adj_returns$portfolio)
sharpe <- mean / vol * sqrt(52)

sharpe
```

```{r}
ts_vol_adj_returns <- xts(vol_adj_returns$portfolio, order.by=vol_adj_returns$date)
sharpe_ratio <- SharpeRatio.annualized(ts_vol_adj_returns, Rf = 0)
sortino_ratio <- SortinoRatio(ts_vol_adj_returns, MAR = 0)
max_drawdown <- maxDrawdown(ts_vol_adj_returns)
annual_return <- Return.annualized(ts_vol_adj_returns)
annual_vol <- sd.annualized(ts_vol_adj_returns)
hit_ratio <- sum(vol_adj_returns$portfolio > 0) / sum(vol_adj_returns$portfolio != 0)

# # Compute Turnover (this is a placeholder; requires portfolio position data)
# # Assuming random turnover for illustration
# turnover <- sum(abs(diff(vol_adj_returns)))

# Create a data frame (table) of portfolio statistics
portfolio_stats <- tibble::tibble(
  Metric = c(
    "Annualized Returns (%)",
    "Annualized Vol (%)",
    "Sharpe Ratio",
    "Sortino Ratio",
    "Maximum Drawdown (%)",
    "Hit Ratio (%)"
    # "Turnover"
    ),
  Value = c(
    round(annual_return[1] * 100, 2),
    round(annual_vol[1] * 100, 2),
    round(sharpe_ratio[1], 2),
    round(sortino_ratio[1], 2),
    round(max_drawdown[1] * 100, 2),
    round(hit_ratio * 100, 2)
    # calmar_ratio,
    # turnover
    )
)

# Print the table
print(portfolio_stats)
```


```{r}
ggplot(data = cum_vol_adj_returns %>%
         select(-date, -portfolio) %>%
         mutate_all(~.+1) %>%
         mutate(date=cum_vol_adj_returns$date) %>%
         melt(., "date"),
       mapping = aes(x = date, y = value, colour = variable, group = variable)) +
  geom_line() +
  scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Cummulative returns in % terms (15% vol target)")
```

```{r}
sharpes <- list()
i <- 1
for (col in colnames(vol_adj_returns %>% select(-date))){
  mean <- mean(vol_adj_returns[[col]])
  vol <- sd(vol_adj_returns[[col]])
  sharpe <- mean / vol * sqrt(52)
  
  sharpes[[i]] <- data.table(currency=col, sharpe=sharpe)
  i <- i + 1
}
sharpes <- do.call(rbind, sharpes) %>% as.data.table()

sharpes
```

```{r}
melted_cor <- melt(get_upper_tri(cor(vol_adj_returns %>% select(-date, -portfolio))), na.rm = TRUE)
ggplot(melted_cor, aes(Var2, Var1, fill = value)) + 
  geom_tile(color = "white") +
  scale_fill_gradient2(low = "blue",
                       high = "red",
                       mid = "white",
                       midpoint = 0,
                       limit = c(-1,1),
                       space = "Lab",
                       name="Pearson\nCorrelation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1))+
  coord_fixed() + 
  theme(axis.title.x = element_blank(), axis.title.y = element_blank())
```

```{r}
decomposition_df <- data.table(date=vol_adj_returns$date,
                               SGD=positions_df$SGD,
                               portfolio_ret=vol_adj_returns$portfolio)
decomposition_df <- decomposition_df %>%
  mutate(`Long USDSGD Ret` := ifelse(SGD > 0, portfolio_ret, 0)) %>%
  mutate(`Short USDSGD Ret` := ifelse(SGD < 0, portfolio_ret, 0))
decomposition_df$`Long USDSGD` <- cumprod(1+(decomposition_df$`Long USDSGD Ret`))
decomposition_df$`Short USDSGD` <- cumprod(1+(decomposition_df$`Short USDSGD Ret`))

ggplot(data = decomposition_df %>%
         select(date, `Long USDSGD`, `Short USDSGD`) %>%
         melt(., "date"),
       mapping = aes(x = date, y = value, colour = variable, group = variable)) +
  geom_line() +
  scale_x_date(date_breaks = "2 year", date_labels = "%b %Y") + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ggtitle("Cummulative returns decomposition for Long or Short USDSGD")
```

```{r}
ts_vol_adj_returns <- xts(decomposition_df$`Long USDSGD Ret`, order.by=decomposition_df$date)
sharpe_ratio <- SharpeRatio.annualized(ts_vol_adj_returns, Rf = 0)
sortino_ratio <- SortinoRatio(ts_vol_adj_returns, MAR = 0)
max_drawdown <- maxDrawdown(ts_vol_adj_returns)
annual_return <- Return.annualized(ts_vol_adj_returns)
annual_vol <- sd.annualized(ts_vol_adj_returns)
hit_ratio <- sum(decomposition_df$`Long USDSGD Ret` > 0) / sum(decomposition_df$`Long USDSGD Ret` != 0)

# # Compute Turnover (this is a placeholder; requires portfolio position data)
# # Assuming random turnover for illustration
# turnover <- sum(abs(diff(vol_adj_returns)))

# Create a data frame (table) of portfolio statistics
portfolio_stats_long <- tibble::tibble(
  Metric = c(
    "Annualized Returns (%)",
    "Annualized Vol (%)",
    "Sharpe Ratio",
    "Sortino Ratio",
    "Maximum Drawdown (%)",
    "Hit Ratio (%)"
    # "Turnover"
    ),
  `Long USDSGD` = c(
    round(annual_return[1] * 100, 2),
    round(annual_vol[1] * 100, 2),
    round(sharpe_ratio[1], 2),
    round(sortino_ratio[1], 2),
    round(max_drawdown[1] * 100, 2),
    round(hit_ratio * 100, 2)
    # calmar_ratio,
    # turnover
    )
)

ts_vol_adj_returns <- xts(decomposition_df$`Short USDSGD Ret`, order.by=decomposition_df$date)
sharpe_ratio <- SharpeRatio.annualized(ts_vol_adj_returns, Rf = 0)
sortino_ratio <- SortinoRatio(ts_vol_adj_returns, MAR = 0)
max_drawdown <- maxDrawdown(ts_vol_adj_returns)
annual_return <- Return.annualized(ts_vol_adj_returns)
annual_vol <- sd.annualized(ts_vol_adj_returns)
hit_ratio <- sum(decomposition_df$`Short USDSGD Ret` > 0) / sum(decomposition_df$`Short USDSGD Ret` != 0)

# # Compute Turnover (this is a placeholder; requires portfolio position data)
# # Assuming random turnover for illustration
# turnover <- sum(abs(diff(vol_adj_returns)))

# Create a data frame (table) of portfolio statistics
portfolio_stats_short <- tibble::tibble(
  Metric = c(
    "Annualized Returns (%)",
    "Annualized Vol (%)",
    "Sharpe Ratio",
    "Sortino Ratio",
    "Maximum Drawdown (%)",
    "Hit Ratio (%)"
    # "Turnover"
    ),
  `Short USDSGD` = c(
    round(annual_return[1] * 100, 2),
    round(annual_vol[1] * 100, 2),
    round(sharpe_ratio[1], 2),
    round(sortino_ratio[1], 2),
    round(max_drawdown[1] * 100, 2),
    round(hit_ratio * 100, 2)
    # calmar_ratio,
    # turnover
    )
)

portfolio_stats_all <- merge(portfolio_stats_long, portfolio_stats_short, by = "Metric")
portfolio_stats_all
```


