---
title: "Drafts"
output: html_notebook
---


```{r}

rm(list=ls())
library('dplyr')
library('ggplot2')
library("lubridate")
library("roll")
library("data.table")

INPUT_PATH <- file.path(getwd(), 'data', 'inputs')

```

Load trade data and betas:

```{r}

currency <- "MYR"
trade_data <- read.csv(file.path(INPUT_PATH, "currencies_trade_data.csv")) %>%
  filter(currency == !!paste0(currency, "  Curncy")) %>% filter((field == "SIMCMALY Index"))
trade_dict <- read.csv(file.path(INPUT_PATH, "currencies_trade_dict.csv"))
pivot_target_trade_data <- dcast(trade_data, date ~ field, value.var = "value") %>% mutate(date=ymd(date))

model <- 'rolling_lm'
scale_type <- 'scale'
path_rolling_lm <- file.path(getwd(), 'data', 'outputs', model, paste0("model_results_", scale_type, ".rds"))

rolling_lm <- readRDS(path_rolling_lm)
coefs_df <- rolling_lm$coefs

target_coefs_df <- coefs_df %>% select(date, !!sym(currency)) %>%
  mutate(date=ymd(date), mean=roll_mean(!!sym(currency), width = 32))

tail(trade_data)
tail(trade_dict)
tail(coefs_df)
```

```{r}
mixed_freq_df <- merge(target_coefs_df , pivot_target_trade_data, by = "date", all.x = TRUE)
melted_mixed_freq_df <- melt(mixed_freq_df, id.vars = "date")
tail(mixed_freq_df)
tail(melted_mixed_freq_df)
```

Plot mixed frequency multivariate time series:


```{r}
melted_mixed_freq_df %>%
  ggplot(aes(date,
             value,
             color = variable,
             group = variable)) +
  geom_line() +
  geom_point(data = filter(total, !is.na(MP) | !is.na(DESCRIPTION))) +
  theme_bw() +
  theme(legend.position = 'top')+
  labs(title = glue::glue("Number of Users over time."),
       subtitle = glue::glue("Interval window of days."),
       y = "",
       x = "")
```

