---
title: "Results Report"
output: html_notebook
---

```{r}
# [1] "/Users/danieloliveira/Documents/Daniel/codes/sgd-trading/src/data/outputs/dlm/model_results_rolling_scale.rds"
rm(list=ls())
library('here')
library('dplyr')
library('ggplot2')
library("aTSA")

OUTPUT_PATH <- file.path(here(), 'src', 'data', 'outputs')
MODEL <- "dlm"
SCALE_TYPE <- "rolling_scale"
STRATEGY_TYPE <- "scale"
FREQ <- "weekly"
WINDOW_SIZE <- 52 * 4
VOL_TARGET <- 10
intercept_tag <- "nointercept"
```

# 0) Load Backtest Results

```{r}
# start_date <- "2008-01-01"
backtest_output <- readRDS(file.path(OUTPUT_PATH, MODEL, SCALE_TYPE, paste0("backtest_results_", FREQ, "_", WINDOW_SIZE, "_", STRATEGY_TYPE, "_", intercept_tag, ".rds")))
model_output <- readRDS(file.path(OUTPUT_PATH, MODEL, SCALE_TYPE,  paste0("model_results_", FREQ, "_", WINDOW_SIZE, "_", intercept_tag, ".rds")))

portfolio_returns <- backtest_output$returns %>% drop_na()
agg_portfolio_returns <- rowSums(portfolio_returns %>% select(-date)) %>% as.data.table() %>% mutate(date=portfolio_returns$date) %>% select(date, everything()) %>% rename("rets":=".")
signals <- backtest_output$signal
positions <- backtest_output$positions
asset_returns <- backtest_output$bars_ret
asset_prices <- backtest_output$bars
if (MODEL == "rolling-ols"){
  coefs <- model_output$model$coefs
}else{
  coefs <- model_output$filter$m
}
```

# 1) Plot Signals

```{r}
ggplot(data = signals %>% select(date, residual) %>% filter(date >= "2000-01-01") %>% melt("date"), 
                   mapping = aes(x = date, y = value, colour = variable, group = variable)) +
              geom_line() +
              scale_x_date(date_breaks = "1 year") + 
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              ggtitle("Residual")

adf.test(x=signals$residual, nlag = 1)

ggplot(data = signals %>% melt("date"), 
                   mapping = aes(x = date, y = value, colour = variable, group = variable)) +
              geom_line() +
              scale_x_date(date_breaks = "1 year") + 
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              ggtitle("Signals and Upper/Lower Bounds")
```

# 2) Plot Beta

```{r}
ggplot(data = coefs %>% melt("date"), 
                   mapping = aes(x = date, y = value, colour = variable, group = variable)) +
              geom_line() +
              scale_x_date(date_breaks = "1 year") + 
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              ggtitle("Beta")

for (i in 2:ncol(coefs)) {
  print(colnames(coefs)[i])
  print(adf.test(x=coefs[[i]], nlag = 1))
}

ar_params = list()
for (i in 2:ncol(coefs)) {
  ts = coefs[[i]]
  # build ar(1) model
  model = arima(ts, order = c(1,0,0), include.mean = FALSE)
  ar_params[[paste0(colnames(coefs)[i])]] = model$coef
}
do.call("cbind", ar_params)
```

# 3) Plot Positions

```{r}
ggplot(data = positions %>% melt("date"), 
                   mapping = aes(x = date, y = value, colour = variable, group = variable)) +
              geom_line() +
              scale_x_date(date_breaks = "1 year") + 
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              ggtitle("Positions")
```

# 3) Plot Raw Cummulative returns

```{r}
portfolio_cumm_rets <- cumprod(1+(portfolio_returns %>% select(-date))) %>% mutate(date=portfolio_returns$date) %>% select(date, everything())
agg_portfolio_cumm_rets <- cumprod(1+(agg_portfolio_returns %>% select(-date))) %>% mutate(date=agg_portfolio_returns$date) %>% select(date, everything())

# each asset
ggplot(data = portfolio_cumm_rets %>% melt("date"), 
                   mapping = aes(x = date, y = value, colour = variable, group = variable)) +
              geom_line() +
              scale_x_date(date_breaks = "1 year") + 
              theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
              ggtitle("Cummulative returns of $1 invested in each asset")

# aggregated portfolio
ggplot(data = agg_portfolio_cumm_rets,
       mapping = aes(x = date, y = rets)) + 
       geom_line() + 
       scale_x_date(date_breaks = "1 year") + 
       theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
       ggtitle("Cummulative returns of $1 invested in the portfolio")

# portfolio metrics for the aggregated portfolio
ret_vec = agg_portfolio_returns %>% select(-date) %>% as.matrix()
list(mean=mean(ret_vec, na.rm = TRUE) * 52,
     vol=sd(ret_vec, na.rm = TRUE) * sqrt(52),
     SR=(mean(ret_vec, na.rm = TRUE) / sd(ret_vec, na.rm = TRUE)) * sqrt(52))
```

# 3) Plot Saceld Cummulative returns

```{r}
scaled_agg_portfolio_returns <- agg_portfolio_returns %>%
mutate(vol=roll_sd(x = rets, width = 12) * sqrt(52) * 100) %>%

agg_portfolio_cumm_rets <- cumprod(1+(agg_portfolio_returns %>% select(-date))) %>% mutate(date=agg_portfolio_returns$date) %>% select(date, everything())

# aggregated portfolio
ggplot(data = agg_portfolio_cumm_rets,
       mapping = aes(x = date, y = rets)) + 
       geom_line() + 
       scale_x_date(date_breaks = "1 year") + 
       theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
       ggtitle("Cummulative returns of $1 invested in the portfolio")

# portfolio metrics for the aggregated portfolio
ret_vec = agg_portfolio_returns %>% select(-date) %>% as.matrix()
list(mean=mean(ret_vec, na.rm = TRUE) * 52,
     vol=sd(ret_vec, na.rm = TRUE) * sqrt(52),
     SR=(mean(ret_vec, na.rm = TRUE) / sd(ret_vec, na.rm = TRUE)) * sqrt(52))
```